### ISSUE TITLE
4_K median 군집화 수정 사항

### ISSUE THREAD

**Issue by dae00a** [public-ai/dl-lecture#3]
안녕하십니까 강사님, 오픈소스 수강중인 이정훈 학생입니다.
네 번째 과제인 K median 군집화에서 사소한 수정 사항을 문의 드리고 싶어서 작성합니다.

In[6]:
```python
cluster_kmeans(arrs,2)
```
6번째 셀의 cluster_kmeans 함수에 arrs 인자가 정의되어 있지 않아 정상적으로 실행되지 않습니다.
전체적인 코드의 설명으로 보아 아래와 같이 수정하면 되는 지 문의드립니다.
```python
arrs = dataset
cluster_kmeans(arrs,2)
```
\
\
\
\
또한 해당 셀의 실행 결과가 아래의 그래프와 같은 경우도 있는데,
군집이 랜덤하게 잡힌다는 의미는 K median을 통해 얻고자 했던 중심점이 도출될 수도 있고
이상치로 인해 원하지 않는 결과가 도출될 수도 있다는 의미로 받아들여도 되는 지 질의드립니다.
\
\
In[7]:
```python
# 군집은 랜덤하게 계속 잡히지만, 
# 우리가 원하지 않은 형태의 군집으로 잡힙니다.
cluster_kmeans(arrs,2)
```
![image](https://user-images.githubusercontent.com/76582834/136507644-a738c88d-1f4d-4e9c-b426-da8cf183c693.png)

항상 유익한 강의 감사합니다.

**Comment by pai-plznw4me** [comment]
@dae00a 안녕하세요. 

### 1
코드에 오류가 있었네요. 죄송합니다. 
arr 에 datasets 을 대신 넣으면 될것 같습니다. 

### 2. 
초기 centroids 랜덤하게 잡기 때문에 k-median 을 통해 구한 최종 centroids 가 다를수는 있습니다. 
하지만 이상치로 원하는 결과가 도출되지 않는걸 확인할려는 의도는 위 숙제에는 없습니다. 
k-means 로는 이상치로 잘못된 결과값이 얻어지는 상황이고 
이상치가 많은 데이터 셋에서는 k-means 가 부적합하고 k-median 을 사용해 에러를 최소화 하는것을 의도로 하고 있습니다. 

감사합니다.
