### ISSUE TITLE
K-means 군집화 질문드립니다

### ISSUE THREAD

**Issue by ghost** [public-ai/dl-lecture#4]
안녕하세요 강사님
오픈소스 AI 응용 수강 중인 SW융합대학 응용컴퓨터공학과 장근덕입니다.

K-means 군집화 과제에서 **dataset과 centroids의 거리를 아래의 조건인 reshape과 broadcasting을 사용하여 한줄로 나타내는 방법에서 어려움을 겪고 있어서 질문 드립니다.**

- "Numpy Code의 reshape와 broadcasting을 활용하면 간결하게 나타낼 수 있습니다."
- "numpy broadcasting 을 활용해 코드 한줄로 모든 centroids 와 모든 데이터간 거리를 계산하세요."

제가 진행한 사항은 다음과 같습니다.
제공된 dataset의 shape은 (80, 2)이고, centroids의 shape은 (4, 2)입니다.
모든 dataset 좌표에 대한 각 centroids와의 거리의 출력으로는 (80, 4) 혹은 (80, 4)의 shape이 요구됩니다.

dataset을 reshape을 통해 (20, 4, 2)로 변환 후 뺄셈 연산을 하여도, 각 data 좌표에 대한 centroids와의 거리가 아닌 의미없는 연산이 됩니다.
또한, dataset을 (80, 4, 2)로 증량시키기에는 concatenate, stack 등을 사용하게 되어도 같은 연산이 반복되어 발생하게 될 뿐입니다.
증량시킬 시 np.insert() 함수를 통해 각 행의 데이터를 중복적으로 추가해야하는 것인지 혹은 다른 insight가 있는 것인지 질문드립니다.

감사합니다.

```python
dists = np.sqrt(np.sum((np.reshape(dataset, (20, 4, 2)) - centroids)**2, axis=2))
dists
```

```python
extended_dataset = np.concatenate((dataset, dataset, dataset, dataset), axis = 0)
dists = np.sqrt(np.sum((np.reshape(extended_dataset , (80, 4, 2)) - centroids)**2, axis=2))
dists
```

**Comment by jkd159** [comment]
np.repeat을 이용하여 데이터를 증량하여 해결하였습니다.
